panda_blog:
    resource: "@PandaExampleBundle/Resources/config/routing.yml"
    prefix:   /

panda_blog2:
    resource: "@PandaExampleBundle/Resources/config/secondRouting.yml"
    prefix:   /second

