geek_hub_blog:
    resource: "@GeekHubBlogBundle/Resources/config/routing.yml"
    prefix:   /

geek_hub_blog2:
    resource: "@GeekHubBlogBundle/Resources/config/secondRouting.yml"
    prefix:   /second

