panda_example_homepage:
    path:     /
    defaults: { _controller: PandaExampleBundle:Default:index }

panda_example_blog:
    path:     /blog
    defaults: { _controller: PandaExampleBundle:Blog:index }

panda_example_blog_post:
    path:     /blog/{id}
    defaults: { _controller: PandaExampleBundle:Blog:post }
    requirements:
            id: '\d+'

panda_example_blog_about:
    path:     /{action}/{slug}
    defaults: { _controller: PandaExampleBundle:Blog:about, action: action, slug: slug }
    requirements:
            action: '\w+'
            slug: '\d+'